feature : Store 캠퍼스 기준 조회 API
everymeals/EveryMeal_Server pull request #55
Opened 2023-10-29 07:47 UTC by Qbeom0925

## 작업 내용
상점 조회 API 개발완료하였습니다.
API의 조회 옵션은 아래 작업 확인 방법과 같이 주었습니다.

## 관련 이슈
#49 

## 작업 확인 방법
<img width="526" alt="스크린샷 2023-10-29 오후 4 45 56" src="https://github.com/everymeals/EveryMeal_Server/assets/53048655/dd451395-162f-4a3d-b0d5-6abafdab13e1">

## 추가 정보 (선택 사항)

2023-10-29 10:27 UTC, dldmsql requested changes

2023-10-29 10:27 UTC, dldmsql commented on src/main/java/everymeal/server/store/controller/StoreController.java
> +                };
이 부분 너무 좋은 거 같아요!

확실히 Swagger에서 테스트할 때, 필요한 데이터만 노출되니까 테스트하기 수월한 거 같아요 👍🏻

2023-10-29 10:27 UTC, dldmsql commented on src/main/java/everymeal/server/store/controller/StoreController.java
> +                };
sorting에 사용되는 값을 상수로 표현하셨는데,

```` java
    /**
     * ============================================================================================
     * GLOBAL STATIC CONSTANTS
     * =============================================================================================
     */
    private final String SORT_NAME = "name";
    private final String SORT_DISTANCE = "distance";
    private final String SORT_RECOMMENDEDCNT = "recommendedCnt";
    private final String SORT_REVIEWCNT = "reviewCount";
    private final String SORT_GRADE = "grade";
````

이렇게 관리하는 건 어떨까요?

2023-11-01 13:49 UTC, Qbeom0925 commented on src/main/java/everymeal/server/store/controller/StoreController.java
> +                };
좋은 생각갔습니다! 일단 컨트롤러에서 선언해서 반영해뒀습니다~

2023-11-02 00:48 UTC, merged